# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://192.168.0.104:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: password
# MyBatis配置
mybatis:
    configuration:
      # 使用驼峰命名法转换字段
      map-underscore-to-camel-case: true
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    # 搜索指定包别名
    type-aliases-package: com.ruoyi.**.domain

# 代码生成
gen:
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.system
  # 自动去除表前缀，默认是false
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

